FROM postgres:17-alpine

COPY container/postgres/init-roles.sh /docker-entrypoint-initdb.d/10-init-roles.sh
RUN sed -i 's/\r$//' /docker-entrypoint-initdb.d/10-init-roles.sh \
  && chmod 755 /docker-entrypoint-initdb.d/10-init-roles.sh \
  && test -x /docker-entrypoint-initdb.d/10-init-roles.sh
