packages:
  - "apps/*"
  - "packages/*"
  - "docs"
catalog:
  hono: ^4.13.7
  "@hono/zod-validator": ^0.7.5
  zod: ^4.1.12
allowBuilds:
  esbuild: true
  protobufjs: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@tanstack/history@1.162.3'
  - '@tanstack/router-cli@1.167.35'
  - '@tanstack/router-core@1.171.29'
  - '@tanstack/router-generator@1.167.35'
  - '@tanstack/router-utils@1.162.3'
